import { uid } from "./time";
import type { Meeting } from "./types";

/** Beyer Loop Fall Y1 — Demo Workday seed. Buildings from the campus brief, not the public classes API. */
export function beyerLoopSeed(): Meeting[] {
  return [
    {
      id: uid("math-lec"),
      course: "MATH 1650",
      title: "Calculus I",
      section: "01",
      format: "Lecture",
      days: ["M", "W", "F"],
      start: "08:50",
      end: "09:40",
      buildingId: "carver",
      color: "#2563eb",
      credits: "4",
      notes: "Night exams scheduled (Registrar).",
    },
    {
      id: uid("math-disc"),
      course: "MATH 1650",
      title: "Calculus I",
      section: "L",
      format: "Discussion",
      days: ["R"],
      start: "12:05",
      end: "12:55",
      buildingId: "carver",
      color: "#2563eb",
      credits: "4",
      notes: "Default Thu 12:05p (alt 8:50a is editable).",
    },
    {
      id: uid("cpre-lec"),
      course: "CPRE 1850",
      title: "Introduction to Computer Engineering and Problem Solving I",
      section: "01",
      format: "Lecture",
      days: ["T", "R"],
      start: "08:50",
      end: "09:40",
      buildingId: "coover",
      color: "#16a34a",
      credits: "3",
    },
    {
      id: uid("cpre-lab"),
      course: "CPRE 1850",
      title: "Introduction to Computer Engineering and Problem Solving I",
      section: "A",
      format: "Laboratory",
      days: ["W"],
      start: "12:05",
      end: "14:00",
      buildingId: "coover",
      color: "#16a34a",
      credits: "3",
    },
    {
      id: uid("engl"),
      course: "ENGL 1500",
      title: "Critical Thinking and Communication",
      section: "11",
      format: "Lecture",
      days: ["M", "W", "F"],
      start: "14:15",
      end: "15:05",
      buildingId: "pearson",
      color: "#7c3aed",
      credits: "3",
    },
    {
      id: uid("chem-lec"),
      course: "CHEM 1670",
      title: "General Chemistry for Engineering Students",
      section: "04",
      format: "Lecture",
      days: ["M", "W", "F"],
      start: "15:20",
      end: "16:10",
      buildingId: "troxel",
      room: "1001",
      color: "#dc2626",
      credits: "4",
    },
    {
      id: uid("chem-disc"),
      course: "CHEM 1670",
      title: "General Chemistry for Engineering Students",
      section: "DE",
      format: "Discussion",
      days: ["T"],
      start: "09:55",
      end: "10:45",
      buildingId: "gilman",
      color: "#dc2626",
      credits: "4",
      notes: "Tue disc at Gilman (open Fall 2026 section DE).",
    },
    {
      id: uid("chem-lab"),
      course: "CHEM 1670",
      title: "General Chemistry for Engineering Students",
      section: "06",
      format: "Laboratory",
      days: ["T"],
      start: "18:10",
      end: "21:00",
      buildingId: "hach",
      color: "#dc2626",
      credits: "4",
      notes: "Tue lab at Hach — only open Tue lab in the Fall 2026 dump. Editable.",
    },
    {
      id: uid("engr"),
      course: "ENGR 1010",
      title: "Engineering Orientation",
      section: "03",
      format: "Lecture",
      days: ["W"],
      start: "08:50",
      end: "09:40",
      buildingId: "hoover",
      color: "#0d9488",
      credits: "R",
      notes: "ECpE section. Overlaps MATH 1650 Lec 01 on Wednesday — flag in grid.",
    },
    {
      id: uid("lib"),
      course: "LIB 1600",
      title: "Introduction to College Level Research",
      section: "10",
      format: "Online",
      days: [],
      start: null,
      end: null,
      buildingId: "online",
      color: "#64748b",
      credits: "1",
      online: true,
      notes: "Online / arranged. Final exam in the ISU Test Center.",
    },
  ];
}
